name: kalkulator_zat_besi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  get: ^4.6.6
  gradient_elevated_button: ^1.0.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  path_provider: ^2.0.8
  universal_platform: ^1.0.0
  calendar_date_picker2: ^1.1.5
  indonesia: ^2.0.0
  sidebarx: ^0.17.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.jpg"


flutter:
  uses-material-design: true
  assets:
    - assets/food_data.json
    - assets/data_index.json
    - assets/pertanyaan1.json
    - assets/pertanyaan2.json
    - assets/images/
    - assets/images/daftar/
    - assets/icon/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Black.ttf
        - asset: assets/fonts/NunitoSans_10pt-BlackItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
        - asset: assets/fonts/NunitoSans_10pt-BoldItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans_10pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-ExtraLight.ttf
        - asset: assets/fonts/NunitoSans_10pt-ExtraLightItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-Italic.ttf
        - asset: assets/fonts/NunitoSans_10pt-Light.ttf
        - asset: assets/fonts/NunitoSans_10pt-LightItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-Medium.ttf
        - asset: assets/fonts/NunitoSans_10pt-MediumItalic.ttf
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/NunitoSans_10pt-SemiBold.ttf
        - asset: assets/fonts/NunitoSans_10pt-SemiBoldItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Black.ttf
        - asset: assets/fonts/NunitoSans_7pt-BlackItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Bold.ttf
        - asset: assets/fonts/NunitoSans_7pt-BoldItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans_7pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-ExtraLight.ttf
        - asset: assets/fonts/NunitoSans_7pt-ExtraLightItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Italic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Light.ttf
        - asset: assets/fonts/NunitoSans_7pt-LightItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Medium.ttf
        - asset: assets/fonts/NunitoSans_7pt-MediumItalic.ttf
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
        - asset: assets/fonts/NunitoSans_7pt-SemiBold.ttf
        - asset: assets/fonts/NunitoSans_7pt-SemiBoldItalic.ttf
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
